// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// CompletionStream represents a model of CompletionStream.
type CompletionStream struct {
}
