// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// AudioSpeechStreamResponse represents a model of AudioSpeechStreamResponse.
type AudioSpeechStreamResponse struct {
}
