// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionRequest represents a model of ChatCompletionRequest.
type ChatCompletionRequest struct {
	ContextLengthExceededBehavior string           `json:"context_length_exceeded_behavior,omitempty"`
	Echo                          bool             `json:"echo,omitempty"`
	FrequencyPenalty              float32          `json:"frequency_penalty,omitempty"`
	LogitBias                     float32          `json:"logit_bias,omitempty"`
	Logprobs                      int32            `json:"logprobs,omitempty"`
	MaxTokens                     int32            `json:"max_tokens,omitempty"`
	Messages                      []map[string]any `json:"messages"`
	MinP                          float32          `json:"min_p,omitempty"`
	PresencePenalty               float32          `json:"presence_penalty,omitempty"`
	RepetitionPenalty             float32          `json:"repetition_penalty,omitempty"`
	ResponseFormat                map[string]any   `json:"response_format,omitempty"`
	SafetyModel                   string           `json:"safety_model,omitempty"`
	Seed                          int32            `json:"seed,omitempty"`
	Stop                          []string         `json:"stop,omitempty"`
	Stream                        bool             `json:"stream,omitempty"`
	Temperature                   float32          `json:"temperature,omitempty"`
	TopK                          int32            `json:"top_k,omitempty"`
	TopP                          float32          `json:"top_p,omitempty"`
}

// GetContextLengthExceededBehavior returns the ContextLengthExceededBehavior field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetContextLengthExceededBehavior() (ret string) {
	if c == nil {
		return ret
	}
	return c.ContextLengthExceededBehavior
}

// GetEcho returns the Echo field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetEcho() (ret bool) {
	if c == nil {
		return ret
	}
	return c.Echo
}

// GetFrequencyPenalty returns the FrequencyPenalty field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetFrequencyPenalty() (ret float32) {
	if c == nil {
		return ret
	}
	return c.FrequencyPenalty
}

// GetLogitBias returns the LogitBias field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetLogitBias() (ret float32) {
	if c == nil {
		return ret
	}
	return c.LogitBias
}

// GetLogprobs returns the Logprobs field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetLogprobs() (ret int32) {
	if c == nil {
		return ret
	}
	return c.Logprobs
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetMaxTokens() (ret int32) {
	if c == nil {
		return ret
	}
	return c.MaxTokens
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetMessages() (ret []map[string]any) {
	if c == nil {
		return ret
	}
	return c.Messages
}

// GetMinP returns the MinP field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetMinP() (ret float32) {
	if c == nil {
		return ret
	}
	return c.MinP
}

// GetPresencePenalty returns the PresencePenalty field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetPresencePenalty() (ret float32) {
	if c == nil {
		return ret
	}
	return c.PresencePenalty
}

// GetRepetitionPenalty returns the RepetitionPenalty field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetRepetitionPenalty() (ret float32) {
	if c == nil {
		return ret
	}
	return c.RepetitionPenalty
}

// GetResponseFormat returns the ResponseFormat field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetResponseFormat() (ret map[string]any) {
	if c == nil {
		return ret
	}
	return c.ResponseFormat
}

// GetSafetyModel returns the SafetyModel field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetSafetyModel() (ret string) {
	if c == nil {
		return ret
	}
	return c.SafetyModel
}

// GetSeed returns the Seed field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetSeed() (ret int32) {
	if c == nil {
		return ret
	}
	return c.Seed
}

// GetStop returns the Stop field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetStop() (ret []string) {
	if c == nil {
		return ret
	}
	return c.Stop
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetStream() (ret bool) {
	if c == nil {
		return ret
	}
	return c.Stream
}

// GetTemperature returns the Temperature field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetTemperature() (ret float32) {
	if c == nil {
		return ret
	}
	return c.Temperature
}

// GetTopK returns the TopK field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetTopK() (ret int32) {
	if c == nil {
		return ret
	}
	return c.TopK
}

// GetTopP returns the TopP field value if set, zero value otherwise.
func (c *ChatCompletionRequest) GetTopP() (ret float32) {
	if c == nil {
		return ret
	}
	return c.TopP
}
