// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// AudioSpeechRequest represents a model of AudioSpeechRequest.
type AudioSpeechRequest struct {
	Input            string  `json:"input"`
	Language         string  `json:"language,omitempty"`
	ResponseEncoding string  `json:"response_encoding,omitempty"`
	ResponseFormat   string  `json:"response_format,omitempty"`
	SampleRate       float32 `json:"sample_rate,omitempty"`
	Stream           bool    `json:"stream,omitempty"`
}

// GetInput returns the Input field value if set, zero value otherwise.
func (a *AudioSpeechRequest) GetInput() (ret string) {
	if a == nil {
		return ret
	}
	return a.Input
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (a *AudioSpeechRequest) GetLanguage() (ret string) {
	if a == nil {
		return ret
	}
	return a.Language
}

// GetResponseEncoding returns the ResponseEncoding field value if set, zero value otherwise.
func (a *AudioSpeechRequest) GetResponseEncoding() (ret string) {
	if a == nil {
		return ret
	}
	return a.ResponseEncoding
}

// GetResponseFormat returns the ResponseFormat field value if set, zero value otherwise.
func (a *AudioSpeechRequest) GetResponseFormat() (ret string) {
	if a == nil {
		return ret
	}
	return a.ResponseFormat
}

// GetSampleRate returns the SampleRate field value if set, zero value otherwise.
func (a *AudioSpeechRequest) GetSampleRate() (ret float32) {
	if a == nil {
		return ret
	}
	return a.SampleRate
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (a *AudioSpeechRequest) GetStream() (ret bool) {
	if a == nil {
		return ret
	}
	return a.Stream
}
