// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// CompletionResponse represents a model of CompletionResponse.
type CompletionResponse struct {
	Choices any            `json:"choices"`
	Created int32          `json:"created"`
	ID      string         `json:"id"`
	Model   string         `json:"model"`
	Object  string         `json:"object"`
	Prompt  any            `json:"prompt,omitempty"`
	Usage   map[string]any `json:"usage"`
}

// GetChoices returns the Choices field value if set, zero value otherwise.
func (c *CompletionResponse) GetChoices() (ret any) {
	if c == nil {
		return ret
	}
	return c.Choices
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (c *CompletionResponse) GetCreated() (ret int32) {
	if c == nil {
		return ret
	}
	return c.Created
}

// GetID returns the ID field value if set, zero value otherwise.
func (c *CompletionResponse) GetID() (ret string) {
	if c == nil {
		return ret
	}
	return c.ID
}

// GetModel returns the Model field value if set, zero value otherwise.
func (c *CompletionResponse) GetModel() (ret string) {
	if c == nil {
		return ret
	}
	return c.Model
}

// GetObject returns the Object field value if set, zero value otherwise.
func (c *CompletionResponse) GetObject() (ret string) {
	if c == nil {
		return ret
	}
	return c.Object
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (c *CompletionResponse) GetPrompt() (ret any) {
	if c == nil {
		return ret
	}
	return c.Prompt
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (c *CompletionResponse) GetUsage() (ret map[string]any) {
	if c == nil {
		return ret
	}
	return c.Usage
}
