// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// HardwareAvailability represents an indicates the current availability status of a hardware configuration.
type HardwareAvailability struct {
	Status string `json:"status"`
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (h *HardwareAvailability) GetStatus() (ret string) {
	if h == nil {
		return ret
	}
	return h.Status
}
