// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionMessageParam represents a model of ChatCompletionMessageParam.
type ChatCompletionMessageParam struct {
}
