// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionTool represents a model of ChatCompletionTool.
type ChatCompletionTool struct {
	Function map[string]any `json:"function"`
	Type     string         `json:"type"`
}

// GetFunction returns the Function field value if set, zero value otherwise.
func (c *ChatCompletionTool) GetFunction() (ret map[string]any) {
	if c == nil {
		return ret
	}
	return c.Function
}

// GetType returns the Type field value if set, zero value otherwise.
func (c *ChatCompletionTool) GetType() (ret string) {
	if c == nil {
		return ret
	}
	return c.Type
}
