// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// StreamSentinel represents a model of StreamSentinel.
type StreamSentinel struct {
	Data string `json:"data"`
}

// GetData returns the Data field value if set, zero value otherwise.
func (s *StreamSentinel) GetData() (ret string) {
	if s == nil {
		return ret
	}
	return s.Data
}
