// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// FinetuneEventLevels represents a model of FinetuneEventLevels.
type FinetuneEventLevels struct {
}
