// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// FinetuneListEvents represents a model of FinetuneListEvents.
type FinetuneListEvents struct {
}
