// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// Autoscaling represents a configuration for automatic scaling of replicas based on demand.
type Autoscaling struct {
	MaxReplicas int32 `json:"max_replicas"`
	MinReplicas int32 `json:"min_replicas"`
}

// GetMaxReplicas returns the MaxReplicas field value if set, zero value otherwise.
func (a *Autoscaling) GetMaxReplicas() (ret int32) {
	if a == nil {
		return ret
	}
	return a.MaxReplicas
}

// GetMinReplicas returns the MinReplicas field value if set, zero value otherwise.
func (a *Autoscaling) GetMinReplicas() (ret int32) {
	if a == nil {
		return ret
	}
	return a.MinReplicas
}
