// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// FineTuneEvent represents a model of FineTuneEvent.
type FineTuneEvent struct {
	CheckpointPath string `json:"checkpoint_path"`
	CreatedAt      string `json:"created_at"`
	Hash           string `json:"hash"`
	Message        string `json:"message"`
	ModelPath      string `json:"model_path"`
	Object         string `json:"object"`
	ParamCount     int32  `json:"param_count"`
	Step           int32  `json:"step"`
	TokenCount     int32  `json:"token_count"`
	TotalSteps     int32  `json:"total_steps"`
	TrainingOffset int32  `json:"training_offset"`
	Type           string `json:"type"`
	WandbURL       string `json:"wandb_url"`
}

// GetCheckpointPath returns the CheckpointPath field value if set, zero value otherwise.
func (f *FineTuneEvent) GetCheckpointPath() (ret string) {
	if f == nil {
		return ret
	}
	return f.CheckpointPath
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (f *FineTuneEvent) GetCreatedAt() (ret string) {
	if f == nil {
		return ret
	}
	return f.CreatedAt
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (f *FineTuneEvent) GetHash() (ret string) {
	if f == nil {
		return ret
	}
	return f.Hash
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (f *FineTuneEvent) GetMessage() (ret string) {
	if f == nil {
		return ret
	}
	return f.Message
}

// GetModelPath returns the ModelPath field value if set, zero value otherwise.
func (f *FineTuneEvent) GetModelPath() (ret string) {
	if f == nil {
		return ret
	}
	return f.ModelPath
}

// GetObject returns the Object field value if set, zero value otherwise.
func (f *FineTuneEvent) GetObject() (ret string) {
	if f == nil {
		return ret
	}
	return f.Object
}

// GetParamCount returns the ParamCount field value if set, zero value otherwise.
func (f *FineTuneEvent) GetParamCount() (ret int32) {
	if f == nil {
		return ret
	}
	return f.ParamCount
}

// GetStep returns the Step field value if set, zero value otherwise.
func (f *FineTuneEvent) GetStep() (ret int32) {
	if f == nil {
		return ret
	}
	return f.Step
}

// GetTokenCount returns the TokenCount field value if set, zero value otherwise.
func (f *FineTuneEvent) GetTokenCount() (ret int32) {
	if f == nil {
		return ret
	}
	return f.TokenCount
}

// GetTotalSteps returns the TotalSteps field value if set, zero value otherwise.
func (f *FineTuneEvent) GetTotalSteps() (ret int32) {
	if f == nil {
		return ret
	}
	return f.TotalSteps
}

// GetTrainingOffset returns the TrainingOffset field value if set, zero value otherwise.
func (f *FineTuneEvent) GetTrainingOffset() (ret int32) {
	if f == nil {
		return ret
	}
	return f.TrainingOffset
}

// GetType returns the Type field value if set, zero value otherwise.
func (f *FineTuneEvent) GetType() (ret string) {
	if f == nil {
		return ret
	}
	return f.Type
}

// GetWandbURL returns the WandbURL field value if set, zero value otherwise.
func (f *FineTuneEvent) GetWandbURL() (ret string) {
	if f == nil {
		return ret
	}
	return f.WandbURL
}
