// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// Pricing represents a model of Pricing.
type Pricing struct {
	Base     float32 `json:"base"`
	Finetune float32 `json:"finetune"`
	Hourly   float32 `json:"hourly"`
	Input    float32 `json:"input"`
	Output   float32 `json:"output"`
}

// GetBase returns the Base field value if set, zero value otherwise.
func (p *Pricing) GetBase() (ret float32) {
	if p == nil {
		return ret
	}
	return p.Base
}

// GetFinetune returns the Finetune field value if set, zero value otherwise.
func (p *Pricing) GetFinetune() (ret float32) {
	if p == nil {
		return ret
	}
	return p.Finetune
}

// GetHourly returns the Hourly field value if set, zero value otherwise.
func (p *Pricing) GetHourly() (ret float32) {
	if p == nil {
		return ret
	}
	return p.Hourly
}

// GetInput returns the Input field value if set, zero value otherwise.
func (p *Pricing) GetInput() (ret float32) {
	if p == nil {
		return ret
	}
	return p.Input
}

// GetOutput returns the Output field value if set, zero value otherwise.
func (p *Pricing) GetOutput() (ret float32) {
	if p == nil {
		return ret
	}
	return p.Output
}
