// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ToolsPart represents a model of ToolsPart.
type ToolsPart struct {
	Function map[string]any `json:"function,omitempty"`
	Type     string         `json:"type,omitempty"`
}

// GetFunction returns the Function field value if set, zero value otherwise.
func (t *ToolsPart) GetFunction() (ret map[string]any) {
	if t == nil {
		return ret
	}
	return t.Function
}

// GetType returns the Type field value if set, zero value otherwise.
func (t *ToolsPart) GetType() (ret string) {
	if t == nil {
		return ret
	}
	return t.Type
}
