// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionUserMessageParam represents a model of ChatCompletionUserMessageParam.
type ChatCompletionUserMessageParam struct {
	Content string `json:"content"`
	Name    string `json:"name,omitempty"`
	Role    string `json:"role"`
}

// GetContent returns the Content field value if set, zero value otherwise.
func (c *ChatCompletionUserMessageParam) GetContent() (ret string) {
	if c == nil {
		return ret
	}
	return c.Content
}

// GetName returns the Name field value if set, zero value otherwise.
func (c *ChatCompletionUserMessageParam) GetName() (ret string) {
	if c == nil {
		return ret
	}
	return c.Name
}

// GetRole returns the Role field value if set, zero value otherwise.
func (c *ChatCompletionUserMessageParam) GetRole() (ret string) {
	if c == nil {
		return ret
	}
	return c.Role
}
