// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// UsageData represents a model of UsageData.
type UsageData struct {
	CompletionTokens int32 `json:"completion_tokens"`
	PromptTokens     int32 `json:"prompt_tokens"`
	TotalTokens      int32 `json:"total_tokens"`
}

// GetCompletionTokens returns the CompletionTokens field value if set, zero value otherwise.
func (u *UsageData) GetCompletionTokens() (ret int32) {
	if u == nil {
		return ret
	}
	return u.CompletionTokens
}

// GetPromptTokens returns the PromptTokens field value if set, zero value otherwise.
func (u *UsageData) GetPromptTokens() (ret int32) {
	if u == nil {
		return ret
	}
	return u.PromptTokens
}

// GetTotalTokens returns the TotalTokens field value if set, zero value otherwise.
func (u *UsageData) GetTotalTokens() (ret int32) {
	if u == nil {
		return ret
	}
	return u.TotalTokens
}
