// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// AudioSpeechStreamEvent represents a model of AudioSpeechStreamEvent.
type AudioSpeechStreamEvent struct {
	Data map[string]any `json:"data"`
}

// GetData returns the Data field value if set, zero value otherwise.
func (a *AudioSpeechStreamEvent) GetData() (ret map[string]any) {
	if a == nil {
		return ret
	}
	return a.Data
}
