// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// CompletionEvent represents a model of CompletionEvent.
type CompletionEvent struct {
	Data map[string]any `json:"data"`
}

// GetData returns the Data field value if set, zero value otherwise.
func (c *CompletionEvent) GetData() (ret map[string]any) {
	if c == nil {
		return ret
	}
	return c.Data
}
