// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// FullTrainingType represents a model of FullTrainingType.
type FullTrainingType struct {
	Type string `json:"type"`
}

// GetType returns the Type field value if set, zero value otherwise.
func (f *FullTrainingType) GetType() (ret string) {
	if f == nil {
		return ret
	}
	return f.Type
}
