// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// LogprobsPart represents a model of LogprobsPart.
type LogprobsPart struct {
	TokenIds      []float32 `json:"token_ids,omitempty"`
	TokenLogprobs []float32 `json:"token_logprobs,omitempty"`
	Tokens        []string  `json:"tokens,omitempty"`
}

// GetTokenIds returns the TokenIds field value if set, zero value otherwise.
func (l *LogprobsPart) GetTokenIds() (ret []float32) {
	if l == nil {
		return ret
	}
	return l.TokenIds
}

// GetTokenLogprobs returns the TokenLogprobs field value if set, zero value otherwise.
func (l *LogprobsPart) GetTokenLogprobs() (ret []float32) {
	if l == nil {
		return ret
	}
	return l.TokenLogprobs
}

// GetTokens returns the Tokens field value if set, zero value otherwise.
func (l *LogprobsPart) GetTokens() (ret []string) {
	if l == nil {
		return ret
	}
	return l.Tokens
}
