// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// EndpointPricing represents a pricing details for using an endpoint.
type EndpointPricing struct {
	CentsPerMinute float32 `json:"cents_per_minute"`
}

// GetCentsPerMinute returns the CentsPerMinute field value if set, zero value otherwise.
func (e *EndpointPricing) GetCentsPerMinute() (ret float32) {
	if e == nil {
		return ret
	}
	return e.CentsPerMinute
}
