// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionToolMessageParam represents a model of ChatCompletionToolMessageParam.
type ChatCompletionToolMessageParam struct {
	Content    string `json:"content"`
	Role       string `json:"role"`
	ToolCallID string `json:"tool_call_id"`
}

// GetContent returns the Content field value if set, zero value otherwise.
func (c *ChatCompletionToolMessageParam) GetContent() (ret string) {
	if c == nil {
		return ret
	}
	return c.Content
}

// GetRole returns the Role field value if set, zero value otherwise.
func (c *ChatCompletionToolMessageParam) GetRole() (ret string) {
	if c == nil {
		return ret
	}
	return c.Role
}

// GetToolCallID returns the ToolCallID field value if set, zero value otherwise.
func (c *ChatCompletionToolMessageParam) GetToolCallID() (ret string) {
	if c == nil {
		return ret
	}
	return c.ToolCallID
}
