// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionToken represents a model of ChatCompletionToken.
type ChatCompletionToken struct {
	ID      int32   `json:"id"`
	Logprob float32 `json:"logprob"`
	Special bool    `json:"special"`
	Text    string  `json:"text"`
}

// GetID returns the ID field value if set, zero value otherwise.
func (c *ChatCompletionToken) GetID() (ret int32) {
	if c == nil {
		return ret
	}
	return c.ID
}

// GetLogprob returns the Logprob field value if set, zero value otherwise.
func (c *ChatCompletionToken) GetLogprob() (ret float32) {
	if c == nil {
		return ret
	}
	return c.Logprob
}

// GetSpecial returns the Special field value if set, zero value otherwise.
func (c *ChatCompletionToken) GetSpecial() (ret bool) {
	if c == nil {
		return ret
	}
	return c.Special
}

// GetText returns the Text field value if set, zero value otherwise.
func (c *ChatCompletionToken) GetText() (ret string) {
	if c == nil {
		return ret
	}
	return c.Text
}
