// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// LoRATrainingType represents a model of LoRATrainingType.
type LoRATrainingType struct {
	LoraAlpha            int32   `json:"lora_alpha"`
	LoraDropout          float32 `json:"lora_dropout,omitempty"`
	LoraR                int32   `json:"lora_r"`
	LoraTrainableModules string  `json:"lora_trainable_modules,omitempty"`
	Type                 string  `json:"type"`
}

// GetLoraAlpha returns the LoraAlpha field value if set, zero value otherwise.
func (l *LoRATrainingType) GetLoraAlpha() (ret int32) {
	if l == nil {
		return ret
	}
	return l.LoraAlpha
}

// GetLoraDropout returns the LoraDropout field value if set, zero value otherwise.
func (l *LoRATrainingType) GetLoraDropout() (ret float32) {
	if l == nil {
		return ret
	}
	return l.LoraDropout
}

// GetLoraR returns the LoraR field value if set, zero value otherwise.
func (l *LoRATrainingType) GetLoraR() (ret int32) {
	if l == nil {
		return ret
	}
	return l.LoraR
}

// GetLoraTrainableModules returns the LoraTrainableModules field value if set, zero value otherwise.
func (l *LoRATrainingType) GetLoraTrainableModules() (ret string) {
	if l == nil {
		return ret
	}
	return l.LoraTrainableModules
}

// GetType returns the Type field value if set, zero value otherwise.
func (l *LoRATrainingType) GetType() (ret string) {
	if l == nil {
		return ret
	}
	return l.Type
}
