// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// LinearLRSchedulerArgs represents a model of LinearLRSchedulerArgs.
type LinearLRSchedulerArgs struct {
	MinLrRatio float32 `json:"min_lr_ratio,omitempty"`
}

// GetMinLrRatio returns the MinLrRatio field value if set, zero value otherwise.
func (l *LinearLRSchedulerArgs) GetMinLrRatio() (ret float32) {
	if l == nil {
		return ret
	}
	return l.MinLrRatio
}
