// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// EmbeddingsResponse represents a model of EmbeddingsResponse.
type EmbeddingsResponse struct {
	Data   []map[string]any `json:"data"`
	Model  string           `json:"model"`
	Object string           `json:"object"`
}

// GetData returns the Data field value if set, zero value otherwise.
func (e *EmbeddingsResponse) GetData() (ret []map[string]any) {
	if e == nil {
		return ret
	}
	return e.Data
}

// GetModel returns the Model field value if set, zero value otherwise.
func (e *EmbeddingsResponse) GetModel() (ret string) {
	if e == nil {
		return ret
	}
	return e.Model
}

// GetObject returns the Object field value if set, zero value otherwise.
func (e *EmbeddingsResponse) GetObject() (ret string) {
	if e == nil {
		return ret
	}
	return e.Object
}
