// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// CompletionChoice represents a model of CompletionChoice.
type CompletionChoice struct {
	Text string `json:"text,omitempty"`
}

// GetText returns the Text field value if set, zero value otherwise.
func (c *CompletionChoice) GetText() (ret string) {
	if c == nil {
		return ret
	}
	return c.Text
}
