// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionStream represents a model of ChatCompletionStream.
type ChatCompletionStream struct {
}
