// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// HardwareSpec represents a detailed specifications of a hardware configuration.
type HardwareSpec struct {
	GpuCount  int32   `json:"gpu_count"`
	GpuLink   string  `json:"gpu_link"`
	GpuMemory float32 `json:"gpu_memory"`
	GpuType   string  `json:"gpu_type"`
}

// GetGpuCount returns the GpuCount field value if set, zero value otherwise.
func (h *HardwareSpec) GetGpuCount() (ret int32) {
	if h == nil {
		return ret
	}
	return h.GpuCount
}

// GetGpuLink returns the GpuLink field value if set, zero value otherwise.
func (h *HardwareSpec) GetGpuLink() (ret string) {
	if h == nil {
		return ret
	}
	return h.GpuLink
}

// GetGpuMemory returns the GpuMemory field value if set, zero value otherwise.
func (h *HardwareSpec) GetGpuMemory() (ret float32) {
	if h == nil {
		return ret
	}
	return h.GpuMemory
}

// GetGpuType returns the GpuType field value if set, zero value otherwise.
func (h *HardwareSpec) GetGpuType() (ret string) {
	if h == nil {
		return ret
	}
	return h.GpuType
}
