// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionResponse represents a model of ChatCompletionResponse.
type ChatCompletionResponse struct {
	Choices any            `json:"choices"`
	Created int32          `json:"created"`
	ID      string         `json:"id"`
	Model   string         `json:"model"`
	Object  string         `json:"object"`
	Usage   map[string]any `json:"usage,omitempty"`
}

// GetChoices returns the Choices field value if set, zero value otherwise.
func (c *ChatCompletionResponse) GetChoices() (ret any) {
	if c == nil {
		return ret
	}
	return c.Choices
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (c *ChatCompletionResponse) GetCreated() (ret int32) {
	if c == nil {
		return ret
	}
	return c.Created
}

// GetID returns the ID field value if set, zero value otherwise.
func (c *ChatCompletionResponse) GetID() (ret string) {
	if c == nil {
		return ret
	}
	return c.ID
}

// GetModel returns the Model field value if set, zero value otherwise.
func (c *ChatCompletionResponse) GetModel() (ret string) {
	if c == nil {
		return ret
	}
	return c.Model
}

// GetObject returns the Object field value if set, zero value otherwise.
func (c *ChatCompletionResponse) GetObject() (ret string) {
	if c == nil {
		return ret
	}
	return c.Object
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (c *ChatCompletionResponse) GetUsage() (ret map[string]any) {
	if c == nil {
		return ret
	}
	return c.Usage
}
