// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// DedicatedEndpoint represents a details about a dedicated endpoint deployment.
type DedicatedEndpoint struct {
	Autoscaling map[string]any `json:"autoscaling"`
	CreatedAt   string         `json:"created_at"`
	DisplayName string         `json:"display_name"`
	Hardware    string         `json:"hardware"`
	ID          string         `json:"id"`
	Model       string         `json:"model"`
	Name        string         `json:"name"`
	Object      string         `json:"object"`
	Owner       string         `json:"owner"`
	State       string         `json:"state"`
	Type        string         `json:"type"`
}

// GetAutoscaling returns the Autoscaling field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetAutoscaling() (ret map[string]any) {
	if d == nil {
		return ret
	}
	return d.Autoscaling
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetCreatedAt() (ret string) {
	if d == nil {
		return ret
	}
	return d.CreatedAt
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetDisplayName() (ret string) {
	if d == nil {
		return ret
	}
	return d.DisplayName
}

// GetHardware returns the Hardware field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetHardware() (ret string) {
	if d == nil {
		return ret
	}
	return d.Hardware
}

// GetID returns the ID field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetID() (ret string) {
	if d == nil {
		return ret
	}
	return d.ID
}

// GetModel returns the Model field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetModel() (ret string) {
	if d == nil {
		return ret
	}
	return d.Model
}

// GetName returns the Name field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetName() (ret string) {
	if d == nil {
		return ret
	}
	return d.Name
}

// GetObject returns the Object field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetObject() (ret string) {
	if d == nil {
		return ret
	}
	return d.Object
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetOwner() (ret string) {
	if d == nil {
		return ret
	}
	return d.Owner
}

// GetState returns the State field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetState() (ret string) {
	if d == nil {
		return ret
	}
	return d.State
}

// GetType returns the Type field value if set, zero value otherwise.
func (d *DedicatedEndpoint) GetType() (ret string) {
	if d == nil {
		return ret
	}
	return d.Type
}
