// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// CompletionChoicesData represents a model of CompletionChoicesData.
type CompletionChoicesData struct {
}
