// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// LRScheduler represents a model of LRScheduler.
type LRScheduler struct {
	LrSchedulerArgs map[string]any `json:"lr_scheduler_args,omitempty"`
	LrSchedulerType string         `json:"lr_scheduler_type"`
}

// GetLrSchedulerArgs returns the LrSchedulerArgs field value if set, zero value otherwise.
func (l *LRScheduler) GetLrSchedulerArgs() (ret map[string]any) {
	if l == nil {
		return ret
	}
	return l.LrSchedulerArgs
}

// GetLrSchedulerType returns the LrSchedulerType field value if set, zero value otherwise.
func (l *LRScheduler) GetLrSchedulerType() (ret string) {
	if l == nil {
		return ret
	}
	return l.LrSchedulerType
}
