// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionChoicesData represents a model of ChatCompletionChoicesData.
type ChatCompletionChoicesData struct {
}
