// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ErrorData represents a model of ErrorData.
type ErrorData struct {
	Error map[string]any `json:"error"`
}

// GetError returns the Error field value if set, zero value otherwise.
func (e *ErrorData) GetError() (ret map[string]any) {
	if e == nil {
		return ret
	}
	return e.Error
}
