// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionAssistantMessageParam represents a model of ChatCompletionAssistantMessageParam.
type ChatCompletionAssistantMessageParam struct {
	Content      string         `json:"content,omitempty"`
	FunctionCall map[string]any `json:"function_call,omitempty"`
	Name         string         `json:"name,omitempty"`
	Role         string         `json:"role"`
}

// GetContent returns the Content field value if set, zero value otherwise.
func (c *ChatCompletionAssistantMessageParam) GetContent() (ret string) {
	if c == nil {
		return ret
	}
	return c.Content
}

// GetFunctionCall returns the FunctionCall field value if set, zero value otherwise.
func (c *ChatCompletionAssistantMessageParam) GetFunctionCall() (ret map[string]any) {
	if c == nil {
		return ret
	}
	return c.FunctionCall
}

// GetName returns the Name field value if set, zero value otherwise.
func (c *ChatCompletionAssistantMessageParam) GetName() (ret string) {
	if c == nil {
		return ret
	}
	return c.Name
}

// GetRole returns the Role field value if set, zero value otherwise.
func (c *ChatCompletionAssistantMessageParam) GetRole() (ret string) {
	if c == nil {
		return ret
	}
	return c.Role
}
