// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ImageResponse represents a model of ImageResponse.
type ImageResponse struct {
	Data  []map[string]any `json:"data"`
	ID    string           `json:"id"`
	Model string           `json:"model"`
}

// GetData returns the Data field value if set, zero value otherwise.
func (i *ImageResponse) GetData() (ret []map[string]any) {
	if i == nil {
		return ret
	}
	return i.Data
}

// GetID returns the ID field value if set, zero value otherwise.
func (i *ImageResponse) GetID() (ret string) {
	if i == nil {
		return ret
	}
	return i.ID
}

// GetModel returns the Model field value if set, zero value otherwise.
func (i *ImageResponse) GetModel() (ret string) {
	if i == nil {
		return ret
	}
	return i.Model
}
