// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// EmbeddingsRequest represents a model of EmbeddingsRequest.
type EmbeddingsRequest struct {
	Model string `json:"model"`
}

// GetModel returns the Model field value if set, zero value otherwise.
func (e *EmbeddingsRequest) GetModel() (ret string) {
	if e == nil {
		return ret
	}
	return e.Model
}
