// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// HardwareWithStatus represents a hardware configuration details with optional availability status.
type HardwareWithStatus struct {
	Availability map[string]any `json:"availability,omitempty"`
	ID           string         `json:"id"`
	Object       string         `json:"object"`
	Pricing      map[string]any `json:"pricing"`
	Specs        map[string]any `json:"specs"`
	UpdatedAt    string         `json:"updated_at"`
}

// GetAvailability returns the Availability field value if set, zero value otherwise.
func (h *HardwareWithStatus) GetAvailability() (ret map[string]any) {
	if h == nil {
		return ret
	}
	return h.Availability
}

// GetID returns the ID field value if set, zero value otherwise.
func (h *HardwareWithStatus) GetID() (ret string) {
	if h == nil {
		return ret
	}
	return h.ID
}

// GetObject returns the Object field value if set, zero value otherwise.
func (h *HardwareWithStatus) GetObject() (ret string) {
	if h == nil {
		return ret
	}
	return h.Object
}

// GetPricing returns the Pricing field value if set, zero value otherwise.
func (h *HardwareWithStatus) GetPricing() (ret map[string]any) {
	if h == nil {
		return ret
	}
	return h.Pricing
}

// GetSpecs returns the Specs field value if set, zero value otherwise.
func (h *HardwareWithStatus) GetSpecs() (ret map[string]any) {
	if h == nil {
		return ret
	}
	return h.Specs
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (h *HardwareWithStatus) GetUpdatedAt() (ret string) {
	if h == nil {
		return ret
	}
	return h.UpdatedAt
}
