// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// RerankRequest represents a model of RerankRequest.
type RerankRequest struct {
	Model           string   `json:"model"`
	Query           string   `json:"query"`
	RankFields      []string `json:"rank_fields,omitempty"`
	ReturnDocuments bool     `json:"return_documents,omitempty"`
	TopN            int32    `json:"top_n,omitempty"`
}

// GetModel returns the Model field value if set, zero value otherwise.
func (r *RerankRequest) GetModel() (ret string) {
	if r == nil {
		return ret
	}
	return r.Model
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (r *RerankRequest) GetQuery() (ret string) {
	if r == nil {
		return ret
	}
	return r.Query
}

// GetRankFields returns the RankFields field value if set, zero value otherwise.
func (r *RerankRequest) GetRankFields() (ret []string) {
	if r == nil {
		return ret
	}
	return r.RankFields
}

// GetReturnDocuments returns the ReturnDocuments field value if set, zero value otherwise.
func (r *RerankRequest) GetReturnDocuments() (ret bool) {
	if r == nil {
		return ret
	}
	return r.ReturnDocuments
}

// GetTopN returns the TopN field value if set, zero value otherwise.
func (r *RerankRequest) GetTopN() (ret int32) {
	if r == nil {
		return ret
	}
	return r.TopN
}
