// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionFunctionMessageParam represents a model of ChatCompletionFunctionMessageParam.
type ChatCompletionFunctionMessageParam struct {
	Content string `json:"content"`
	Name    string `json:"name"`
	Role    string `json:"role"`
}

// GetContent returns the Content field value if set, zero value otherwise.
func (c *ChatCompletionFunctionMessageParam) GetContent() (ret string) {
	if c == nil {
		return ret
	}
	return c.Content
}

// GetName returns the Name field value if set, zero value otherwise.
func (c *ChatCompletionFunctionMessageParam) GetName() (ret string) {
	if c == nil {
		return ret
	}
	return c.Name
}

// GetRole returns the Role field value if set, zero value otherwise.
func (c *ChatCompletionFunctionMessageParam) GetRole() (ret string) {
	if c == nil {
		return ret
	}
	return c.Role
}
