// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ListEndpoint represents a details about an endpoint when listed via the list endpoint.
type ListEndpoint struct {
	CreatedAt string `json:"created_at"`
	ID        string `json:"id"`
	Model     string `json:"model"`
	Name      string `json:"name"`
	Object    string `json:"object"`
	Owner     string `json:"owner"`
	State     string `json:"state"`
	Type      string `json:"type"`
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (l *ListEndpoint) GetCreatedAt() (ret string) {
	if l == nil {
		return ret
	}
	return l.CreatedAt
}

// GetID returns the ID field value if set, zero value otherwise.
func (l *ListEndpoint) GetID() (ret string) {
	if l == nil {
		return ret
	}
	return l.ID
}

// GetModel returns the Model field value if set, zero value otherwise.
func (l *ListEndpoint) GetModel() (ret string) {
	if l == nil {
		return ret
	}
	return l.Model
}

// GetName returns the Name field value if set, zero value otherwise.
func (l *ListEndpoint) GetName() (ret string) {
	if l == nil {
		return ret
	}
	return l.Name
}

// GetObject returns the Object field value if set, zero value otherwise.
func (l *ListEndpoint) GetObject() (ret string) {
	if l == nil {
		return ret
	}
	return l.Object
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (l *ListEndpoint) GetOwner() (ret string) {
	if l == nil {
		return ret
	}
	return l.Owner
}

// GetState returns the State field value if set, zero value otherwise.
func (l *ListEndpoint) GetState() (ret string) {
	if l == nil {
		return ret
	}
	return l.State
}

// GetType returns the Type field value if set, zero value otherwise.
func (l *ListEndpoint) GetType() (ret string) {
	if l == nil {
		return ret
	}
	return l.Type
}
