// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// RerankResponse represents a model of RerankResponse.
type RerankResponse struct {
	ID      string           `json:"id,omitempty"`
	Model   string           `json:"model"`
	Object  string           `json:"object"`
	Results []map[string]any `json:"results"`
	Usage   map[string]any   `json:"usage,omitempty"`
}

// GetID returns the ID field value if set, zero value otherwise.
func (r *RerankResponse) GetID() (ret string) {
	if r == nil {
		return ret
	}
	return r.ID
}

// GetModel returns the Model field value if set, zero value otherwise.
func (r *RerankResponse) GetModel() (ret string) {
	if r == nil {
		return ret
	}
	return r.Model
}

// GetObject returns the Object field value if set, zero value otherwise.
func (r *RerankResponse) GetObject() (ret string) {
	if r == nil {
		return ret
	}
	return r.Object
}

// GetResults returns the Results field value if set, zero value otherwise.
func (r *RerankResponse) GetResults() (ret []map[string]any) {
	if r == nil {
		return ret
	}
	return r.Results
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (r *RerankResponse) GetUsage() (ret map[string]any) {
	if r == nil {
		return ret
	}
	return r.Usage
}
