// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// FileResponse represents a model of FileResponse.
type FileResponse struct {
	LineCount int32  `json:"LineCount"`
	Processed bool   `json:"Processed"`
	Bytes     int32  `json:"bytes"`
	CreatedAt int32  `json:"created_at"`
	Filename  string `json:"filename"`
	ID        string `json:"id"`
	Object    string `json:"object"`
}

// GetLineCount returns the LineCount field value if set, zero value otherwise.
func (f *FileResponse) GetLineCount() (ret int32) {
	if f == nil {
		return ret
	}
	return f.LineCount
}

// GetProcessed returns the Processed field value if set, zero value otherwise.
func (f *FileResponse) GetProcessed() (ret bool) {
	if f == nil {
		return ret
	}
	return f.Processed
}

// GetBytes returns the Bytes field value if set, zero value otherwise.
func (f *FileResponse) GetBytes() (ret int32) {
	if f == nil {
		return ret
	}
	return f.Bytes
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (f *FileResponse) GetCreatedAt() (ret int32) {
	if f == nil {
		return ret
	}
	return f.CreatedAt
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (f *FileResponse) GetFilename() (ret string) {
	if f == nil {
		return ret
	}
	return f.Filename
}

// GetID returns the ID field value if set, zero value otherwise.
func (f *FileResponse) GetID() (ret string) {
	if f == nil {
		return ret
	}
	return f.ID
}

// GetObject returns the Object field value if set, zero value otherwise.
func (f *FileResponse) GetObject() (ret string) {
	if f == nil {
		return ret
	}
	return f.Object
}
