// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// AudioSpeechStreamChunk represents a model of AudioSpeechStreamChunk.
type AudioSpeechStreamChunk struct {
	B64    string `json:"b64"`
	Model  string `json:"model"`
	Object string `json:"object"`
}

// GetB64 returns the B64 field value if set, zero value otherwise.
func (a *AudioSpeechStreamChunk) GetB64() (ret string) {
	if a == nil {
		return ret
	}
	return a.B64
}

// GetModel returns the Model field value if set, zero value otherwise.
func (a *AudioSpeechStreamChunk) GetModel() (ret string) {
	if a == nil {
		return ret
	}
	return a.Model
}

// GetObject returns the Object field value if set, zero value otherwise.
func (a *AudioSpeechStreamChunk) GetObject() (ret string) {
	if a == nil {
		return ret
	}
	return a.Object
}
