// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// FinetuneEventType represents a model of FinetuneEventType.
type FinetuneEventType struct {
}
