// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// FileDeleteResponse represents a model of FileDeleteResponse.
type FileDeleteResponse struct {
	Deleted bool   `json:"deleted,omitempty"`
	ID      string `json:"id,omitempty"`
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (f *FileDeleteResponse) GetDeleted() (ret bool) {
	if f == nil {
		return ret
	}
	return f.Deleted
}

// GetID returns the ID field value if set, zero value otherwise.
func (f *FileDeleteResponse) GetID() (ret string) {
	if f == nil {
		return ret
	}
	return f.ID
}
