// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// ChatCompletionMessage represents a model of ChatCompletionMessage.
type ChatCompletionMessage struct {
	Content      string         `json:"content"`
	FunctionCall map[string]any `json:"function_call,omitempty"`
	Role         string         `json:"role"`
}

// GetContent returns the Content field value if set, zero value otherwise.
func (c *ChatCompletionMessage) GetContent() (ret string) {
	if c == nil {
		return ret
	}
	return c.Content
}

// GetFunctionCall returns the FunctionCall field value if set, zero value otherwise.
func (c *ChatCompletionMessage) GetFunctionCall() (ret map[string]any) {
	if c == nil {
		return ret
	}
	return c.FunctionCall
}

// GetRole returns the Role field value if set, zero value otherwise.
func (c *ChatCompletionMessage) GetRole() (ret string) {
	if c == nil {
		return ret
	}
	return c.Role
}
