// Code generated by github.com/zchee/go-openapi-tools/cmd/oapi-generator. DO NOT EDIT.

package togetherai

// FinetuneJobStatus represents a model of FinetuneJobStatus.
type FinetuneJobStatus struct {
}
